### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [ ]:
# 2D and 3D
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [4]:
# np.arange
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
# with reshape
np.arange(12).reshape(2,2,3).shape

(2, 2, 3)

In [ ]:
# np.ones and np.zeros
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros(12).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.30627827, 0.2983709 , 0.1492981 , 0.32457499],
       [0.12508836, 0.13369581, 0.2678704 , 0.738689  ],
       [0.33141428, 0.18235918, 0.29739391, 0.61667997]])

In [10]:
# np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [12]:
arr1 = np.arange(8, dtype=np.int32).reshape(2,2,2)
arr2 = np.arange(12, dtype=float).reshape(4,3)
arr3 = np.arange(8).reshape(2,4)

In [ ]:
# ndim
arr1.ndim

3

In [ ]:
# shape
arr1.shape

(2, 2, 2)

In [13]:
# size
arr2.size

12

In [ ]:
# itemsize
arr2.itemsize

8

In [16]:
# dtype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
arr3.astype(np.int32)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [22]:
# relational
a4 = a1 == 14
a4

array([False, False, False])

In [ ]:
# vector operations
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [ ]:
arr1 = np.random.random((3,3))*100
arr1 = np.round(arr1)
arr2 = np.arange(9).reshape(3,3)

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(arr1)

91.0

In [ ]:
# mean/median/std/var
np.var(arr1)

820.3209876543209

In [ ]:
# trigonomoetric functions
np.sin(arr1)

array([[ 0.76255845,  0.91294525,  0.77389068],
       [ 0.14112001,  0.10598751, -0.55878905],
       [ 0.55142668, -0.28790332, -0.7568025 ]])

In [ ]:
# dot product
np.dot(arr1, arr2)

array([[468., 646., 824.],
       [369., 509., 649.],
       [336., 448., 560.]])

In [ ]:
# log and exponents
log1 = np.log(arr1)
log1

array([[4.51085951, 2.89037176, 4.2341065 ],
       [4.15888308, 3.36729583, 3.8501476 ],
       [3.63758616, 3.58351894, 3.63758616]])

In [ ]:
# round/floor/ceil
np.ceil(log1)

array([[5., 3., 5.],
       [5., 4., 4.],
       [4., 4., 4.]])

### Indexing and Slicing

In [31]:
a1 = np.arange(10)
a2 = np.arange(9).reshape(3,3)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
a2 = a2[a2 > 3]
a2

array([4, 5, 6, 7, 8])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a2[1,1]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a4 = np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a4[:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a4[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a4[1,::3]

array([4, 7])

In [ ]:
a4[0]

array([0, 1, 2, 3])

In [ ]:
a4[:,2]

array([ 2,  6, 10])

In [ ]:
a4[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a5 = np.arange(27).reshape(3,3,3)
a5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a5[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a5[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a5[0,1]

array([3, 4, 5])

### Iterating

In [ ]:
for i in a1:
   print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a4:
   print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a5

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a5:
   print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a5):
   print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

ValueError: ignored

In [ ]:
# vertical splitting

In [26]:
a1

array([1, 2, 3])

ValueError: ignored